### ISSUE TITLE
rejecting incoming call does not hang up remote phone

### ISSUE THREAD

**Issue by fuchsnj** [bandwidthcom/bandwidth-webrtc#56]
see https://github.com/inetCatapult/reg-ansible/issues/81

**Comment by wtcross** [comment]
This is not an issue with `webrtc-client`. I'm going to close the issue and reopen in the edge repo.

**Comment by wtcross** [comment]
On second thought, `webrtc-client` could help with the issue by always making a best effort to `unregister` the user on window unload (tab close, refresh). @fuchsnj, are you confident in the code that does that? I remember adding it at some point.

**Comment by wtcross** [comment]
The issue occurs when there is more than one contact associated with a registered user. This happens (currently) if you refresh the page several times. The user is not unregistered before the page unloads.

**Comment by wtcross** [comment]
[This](https://github.com/bandwidthcom/webrtc-client/blob/master/lib/BWClient.js#L9) code needs to be manually tested.

**Comment by wtcross** [comment]
This is at least the third time an issue has popped up because of no real functional tests. We need those soon

**Comment by wtcross** [comment]
If there is only one contact associated with your user then rejecting calls works. This is a stupid problem, I know. I'm fixing it upstream.

**Comment by wtcross** [comment]
This issue has been resolved upstream. The behaviour was caused by an OpenSIPS registrar picking a `430 Flow Failed` reply from the outbound edge proxy that this client connects to. This reply is sent when a message is sent via a websocket connection that no longer exists.
